name: housing
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pandas=2.1.1
- scikit-learn=1.3.1
# Data visualization and analysis
- matplotlib>=3.7.0
- seaborn>=0.12.0
- scipy>=1.11.0
# FastAPI and web framework dependencies
- fastapi>=0.104.0
- uvicorn[standard]>=0.24.0
- pydantic>=2.4.0
# Additional utility dependencies
- python-multipart  # For form data handling
- python-jose[cryptography]  # For JWT tokens (if needed later)
- passlib[bcrypt]  # For password hashing (if needed later)
# Development and testing dependencies
- pytest>=7.4.0
- pytest-asyncio>=0.21.0
- httpx>=0.25.0  # For testing FastAPI endpoints
# Pip dependencies that might not be available via conda
- pip
- pip:
  - python-dotenv>=1.0.0  # For environment variable management
  - pydantic-settings>=2.0.0  # For Pydantic v2 BaseSettings
  - requests>=2.31.0  # For API testing